const SAMPLE_EVENTS = [
    {
        id: 1,
        title: "Major cocaine shipment seized at Rotterdam port",
        description: "Dutch customs officials discovered 8,200 kg of cocaine hidden inside a container of fruit arriving from South America. The shipment originated from Ecuador and was destined for distribution across Western Europe. Five suspects arrested in coordinated raids across Rotterdam and Amsterdam.",
        event_time: "2025-06-08T14:30:00Z",
        lat: 51.9244,
        lng: 4.4777,
        country: "NLD",
        city: "Rotterdam",
        category: "port_interdiction",
        drug_type: "cocaine",
        quantity_kg: 8200,
        source_url: "https://example.com/rotterdam-seizure",
        source_name: "Dutch Customs",
        status: "verified"
    },
    {
        id: 2,
        title: "Synthetic drug lab dismantled in Brabant",
        description: "Dutch police dismantled a large-scale synthetic drug laboratory in North Brabant producing MDMA and amphetamines. Over 500 liters of chemical precursors seized along with industrial pill presses capable of producing 100,000 tablets per hour.",
        event_time: "2025-06-07T09:15:00Z",
        lat: 51.4826,
        lng: 5.2325,
        country: "NLD",
        city: "Eindhoven",
        category: "lab_bust",
        drug_type: "synthetic",
        quantity_kg: null,
        source_url: "https://example.com/brabant-lab",
        source_name: "Dutch Police",
        status: "verified"
    },
    {
        id: 3,
        title: "Spanish police arrest hashish trafficking network",
        description: "Guardia Civil arrested 23 people in a crackdown on a hashish trafficking network operating between Morocco and southern Spain. Over 6,000 kg of hashish resin seized along with 12 vessels used for smuggling across the Strait of Gibraltar.",
        event_time: "2025-06-06T16:45:00Z",
        lat: 36.7213,
        lng: -4.4214,
        country: "ESP",
        city: "Málaga",
        category: "arrest",
        drug_type: "cannabis",
        quantity_kg: 6000,
        source_url: "https://example.com/spain-hashish",
        source_name: "Guardia Civil",
        status: "verified"
    },
    {
        id: 4,
        title: "Fentanyl trafficking ring busted in Berlin",
        description: "German federal police dismantled a fentanyl distribution network operating in Berlin and Brandenburg. The group was importing fentanyl analogues from China via dark web marketplaces and distributing through local dealer networks. 50,000 doses seized.",
        event_time: "2025-06-06T11:00:00Z",
        lat: 52.5200,
        lng: 13.4050,
        country: "DEU",
        city: "Berlin",
        category: "dark_web",
        drug_type: "fentanyl",
        quantity_kg: 0.5,
        source_url: "https://example.com/berlin-fentanyl",
        source_name: "BKA",
        status: "verified"
    },
    {
        id: 5,
        title: "Record heroin seizure at Greek-Turkish border",
        description: "Greek border police intercepted 340 kg of heroin hidden in a truck at the Kipi border crossing with Turkey. The truck was carrying commercial goods destined for Germany. Three Turkish nationals arrested.",
        event_time: "2025-06-05T08:20:00Z",
        lat: 40.9260,
        lng: 25.8960,
        country: "GRC",
        city: "Kipi",
        category: "seizure",
        drug_type: "heroin",
        quantity_kg: 340,
        source_url: "https://example.com/greece-heroin",
        source_name: "Greek Police",
        status: "verified"
    },
    {
        id: 6,
        title: "Cocaine hidden in banana shipment, Antwerp port",
        description: "Belgian customs seized 4,500 kg of cocaine concealed in a banana shipment from Colombia at the Port of Antwerp. The port has become Europe's largest cocaine entry point, with seizures doubling over the past five years.",
        event_time: "2025-06-05T06:30:00Z",
        lat: 51.2194,
        lng: 4.4025,
        country: "BEL",
        city: "Antwerp",
        category: "port_interdiction",
        drug_type: "cocaine",
        quantity_kg: 4500,
        source_url: "https://example.com/antwerp-cocaine",
        source_name: "Belgian Customs",
        status: "verified"
    },
    {
        id: 7,
        title: "MDMA production facility discovered in Limburg",
        description: "Belgian federal police discovered an underground MDMA production facility in a former mushroom farm in Limburg province. 1.2 million ecstasy tablets and 300 liters of MDMA oil seized. Four suspects, including two Dutch nationals, arrested.",
        event_time: "2025-06-04T13:00:00Z",
        lat: 50.9646,
        lng: 5.5062,
        country: "BEL",
        city: "Maasmechelen",
        category: "lab_bust",
        drug_type: "mdma",
        quantity_kg: 450,
        source_url: "https://example.com/limburg-mdma",
        source_name: "Belgian Federal Police",
        status: "verified"
    },
    {
        id: 8,
        title: "Italian mafia drug operation dismantled in Calabria",
        description: "Italian Carabinieri arrested 48 people linked to the 'Ndrangheta mafia in a major anti-drug operation across Calabria. The network controlled cocaine importation from South America through the port of Gioia Tauro, one of the largest container ports in the Mediterranean.",
        event_time: "2025-06-04T07:00:00Z",
        lat: 38.4130,
        lng: 15.8450,
        country: "ITA",
        city: "Gioia Tauro",
        category: "arrest",
        drug_type: "cocaine",
        quantity_kg: 2800,
        source_url: "https://example.com/calabria-mafia",
        source_name: "Carabinieri",
        status: "verified"
    },
    {
        id: 9,
        title: "Overdose spike alert in Dublin city center",
        description: "Dublin health services issued an alert after 14 overdose incidents were recorded in a single weekend in the city center. Suspected heroin laced with fentanyl. Needle exchange programs and emergency services overwhelmed.",
        event_time: "2025-06-03T19:30:00Z",
        lat: 53.3498,
        lng: -6.2603,
        country: "IRL",
        city: "Dublin",
        category: "overdose",
        drug_type: "heroin",
        quantity_kg: null,
        source_url: "https://example.com/dublin-overdose",
        source_name: "HSE Ireland",
        status: "verified"
    },
    {
        id: 10,
        title: "Darknet marketplace 'CannabisRoad' shut down",
        description: "Europol coordinated the takedown of a major dark web drug marketplace operating from servers in Germany and the Netherlands. The platform facilitated sales of cannabis, MDMA, and LSD worth an estimated €25 million over 18 months. 12 administrators arrested.",
        event_time: "2025-06-03T10:00:00Z",
        lat: 52.3676,
        lng: 4.9041,
        country: "NLD",
        city: "Amsterdam",
        category: "dark_web",
        drug_type: "other",
        quantity_kg: null,
        source_url: "https://example.com/darknet-takedown",
        source_name: "Europol",
        status: "verified"
    },
    {
        id: 11,
        title: "Portugal decriminalization review published",
        description: "Portugal's government published a comprehensive review of its drug decriminalization policy after 23 years. The report recommends adjustments to the framework including increased investment in treatment facilities and harm reduction programs.",
        event_time: "2025-06-02T12:00:00Z",
        lat: 38.7223,
        lng: -9.1393,
        country: "PRT",
        city: "Lisbon",
        category: "policy",
        drug_type: "other",
        quantity_kg: null,
        source_url: "https://example.com/portugal-policy",
        source_name: "Portuguese Government",
        status: "verified"
    },
    {
        id: 12,
        title: "Methamphetamine lab discovered in Czech-Polish border",
        description: "Joint Czech-Polish police operation discovered a methamphetamine production facility near the border town of Cieszyn. 15 kg of crystal meth and large quantities of pseudoephedrine precursors seized. Six suspects arrested on both sides of the border.",
        event_time: "2025-06-02T08:45:00Z",
        lat: 49.7466,
        lng: 18.6368,
        country: "CZE",
        city: "Cieszyn",
        category: "lab_bust",
        drug_type: "synthetic",
        quantity_kg: 15,
        source_url: "https://example.com/czech-meth",
        source_name: "Czech Police",
        status: "verified"
    },
    {
        id: 13,
        title: "France seizes 1.2 tonnes of cannabis near Nice",
        description: "French Gendarmerie intercepted 1,200 kg of cannabis resin in a truck on the A8 motorway near Nice. The shipment originated from Spain and was destined for the Paris region. Two French nationals and one Spanish national arrested.",
        event_time: "2025-06-01T15:30:00Z",
        lat: 43.7102,
        lng: 7.2620,
        country: "FRA",
        city: "Nice",
        category: "seizure",
        drug_type: "cannabis",
        quantity_kg: 1200,
        source_url: "https://example.com/nice-cannabis",
        source_name: "Gendarmerie",
        status: "verified"
    },
    {
        id: 14,
        title: "Balkan trafficking route: heroin shipment intercepted in Serbia",
        description: "Serbian police seized 120 kg of heroin from a truck at the Horgoš border crossing with Hungary. The heroin was being transported along the traditional Balkan route from Turkey through Bulgaria and Serbia toward Western Europe.",
        event_time: "2025-06-01T06:00:00Z",
        lat: 46.0667,
        lng: 19.6000,
        country: "SRB",
        city: "Horgoš",
        category: "route",
        drug_type: "heroin",
        quantity_kg: 120,
        source_url: "https://example.com/serbia-heroin",
        source_name: "Serbian Police",
        status: "verified"
    },
    {
        id: 15,
        title: "Cocaine washing up on beaches in Normandy",
        description: "Over 300 kg of cocaine in waterproof packages washed up on multiple beaches along the Normandy coast over the past week. Authorities believe the drugs were jettisoned from a cargo ship and carried by currents. Coast guard patrols increased.",
        event_time: "2025-05-31T10:00:00Z",
        lat: 49.1829,
        lng: -0.3707,
        country: "FRA",
        city: "Caen",
        category: "seizure",
        drug_type: "cocaine",
        quantity_kg: 300,
        source_url: "https://example.com/normandy-cocaine",
        source_name: "French Coast Guard",
        status: "verified"
    },
    {
        id: 16,
        title: "Estonia reports spike in fentanyl overdoses",
        description: "Estonian health authorities reported a 40% increase in opioid overdose deaths in Tallinn, primarily linked to fentanyl and its analogues. Estonia has one of the highest rates of fentanyl-related deaths in the EU. Mobile overdose prevention units deployed.",
        event_time: "2025-05-30T14:00:00Z",
        lat: 59.4370,
        lng: 24.7536,
        country: "EST",
        city: "Tallinn",
        category: "overdose",
        drug_type: "fentanyl",
        quantity_kg: null,
        source_url: "https://example.com/estonia-fentanyl",
        source_name: "Estonian Health Board",
        status: "verified"
    },
    {
        id: 17,
        title: "Major amphetamine seizure at Swedish port",
        description: "Swedish Customs seized 800 kg of amphetamine at the Port of Helsingborg, arriving in a container from the Netherlands. The drugs were concealed inside furniture. Three people arrested in a follow-up operation in Stockholm.",
        event_time: "2025-05-30T07:30:00Z",
        lat: 56.0465,
        lng: 12.6945,
        country: "SWE",
        city: "Helsingborg",
        category: "port_interdiction",
        drug_type: "synthetic",
        quantity_kg: 800,
        source_url: "https://example.com/sweden-amphetamine",
        source_name: "Swedish Customs",
        status: "verified"
    },
    {
        id: 18,
        title: "Albanian police destroy cannabis plantations",
        description: "Albanian State Police destroyed over 50,000 cannabis plants in coordinated operations across the southern districts of Vlorë and Gjirokastër. The plants were being cultivated for export to Italy and Greece via speedboats across the Adriatic.",
        event_time: "2025-05-29T09:00:00Z",
        lat: 40.4663,
        lng: 19.4892,
        country: "ALB",
        city: "Vlorë",
        category: "seizure",
        drug_type: "cannabis",
        quantity_kg: 15000,
        source_url: "https://example.com/albania-cannabis",
        source_name: "Albanian State Police",
        status: "verified"
    },
    {
        id: 19,
        title: "Europol-coordinated operation targets synthetic drug traffickers",
        description: "Europol coordinated a Europe-wide operation targeting synthetic drug production and trafficking networks. Over 500 police officers involved in raids across 8 countries. 150 arrests, 23 labs dismantled, 3.5 tonnes of synthetic drugs seized.",
        event_time: "2025-05-28T08:00:00Z",
        lat: 52.0705,
        lng: 4.3007,
        country: "NLD",
        city: "The Hague",
        category: "arrest",
        drug_type: "synthetic",
        quantity_kg: 3500,
        source_url: "https://example.com/europol-operation",
        source_name: "Europol",
        status: "verified"
    },
    {
        id: 20,
        title: "Heroin trafficking network dismantled in Vienna",
        description: "Austrian police dismantled a heroin trafficking network that had been importing heroin from Turkey via the Balkan route and distributing it in Vienna and Graz. 45 kg of heroin seized, along with €500,000 in cash. 15 people arrested.",
        event_time: "2025-05-28T06:00:00Z",
        lat: 48.2082,
        lng: 16.3738,
        country: "AUT",
        city: "Vienna",
        category: "arrest",
        drug_type: "heroin",
        quantity_kg: 45,
        source_url: "https://example.com/vienna-heroin",
        source_name: "Austrian Police",
        status: "verified"
    },
    {
        id: 21,
        title: "Cocaine seized at Hamburg port in shipping containers",
        description: "German customs discovered 3,100 kg of cocaine in three shipping containers at the Port of Hamburg. The containers originated from Paraguay and were declared as carrying soy products. Six suspects arrested in Hamburg and Bremen.",
        event_time: "2025-05-27T11:30:00Z",
        lat: 53.5511,
        lng: 9.9937,
        country: "DEU",
        city: "Hamburg",
        category: "port_interdiction",
        drug_type: "cocaine",
        quantity_kg: 3100,
        source_url: "https://example.com/hamburg-cocaine",
        source_name: "German Customs",
        status: "verified"
    },
    {
        id: 22,
        title: "Poland: Massive MDMA lab found in suburban warehouse",
        description: "Polish Central Bureau of Investigation discovered an MDMA laboratory in a warehouse complex near Warsaw. 200 kg of MDMA crystals and 500,000 ecstasy pills seized. The operation was linked to Dutch organized crime groups supplying the Scandinavian market.",
        event_time: "2025-05-26T14:00:00Z",
        lat: 52.2297,
        lng: 21.0122,
        country: "POL",
        city: "Warsaw",
        category: "lab_bust",
        drug_type: "mdma",
        quantity_kg: 200,
        source_url: "https://example.com/warsaw-mdma",
        source_name: "CBŚP",
        status: "verified"
    },
    {
        id: 23,
        title: "UK classifies new synthetic cannabinoid as Class A",
        description: "The UK Home Office announced the reclassification of a new synthetic cannabinoid (MDMB-4en-PINACA) as a Class A drug following a spike in hospitalizations. The substance had been linked to 12 deaths in the past six months.",
        event_time: "2025-05-26T10:00:00Z",
        lat: 51.5074,
        lng: -0.1278,
        country: "GBR",
        city: "London",
        category: "policy",
        drug_type: "synthetic",
        quantity_kg: null,
        source_url: "https://example.com/uk-policy",
        source_name: "UK Home Office",
        status: "verified"
    },
    {
        id: 24,
        title: "Croatian coast guard intercepts speedboat carrying cannabis",
        description: "Croatian coast guard intercepted a high-speed boat carrying 800 kg of cannabis resin near the island of Vis. The boat had launched from the Albanian coast and was attempting to reach Italy. Two suspects arrested after a brief chase.",
        event_time: "2025-05-25T22:00:00Z",
        lat: 43.0411,
        lng: 16.1922,
        country: "HRV",
        city: "Vis",
        category: "seizure",
        drug_type: "cannabis",
        quantity_kg: 800,
        source_url: "https://example.com/croatia-speedboat",
        source_name: "Croatian Coast Guard",
        status: "verified"
    },
    {
        id: 25,
        title: "Finland dismantles domestic amphetamine production ring",
        description: "Finnish National Bureau of Investigation dismantled a domestic amphetamine production network operating across southern Finland. Three small-scale laboratories raided, 12 kg of amphetamine seized along with precursors and equipment. Seven arrests made.",
        event_time: "2025-05-25T07:00:00Z",
        lat: 60.1699,
        lng: 24.9384,
        country: "FIN",
        city: "Helsinki",
        category: "lab_bust",
        drug_type: "synthetic",
        quantity_kg: 12,
        source_url: "https://example.com/finland-amphetamine",
        source_name: "NBI Finland",
        status: "verified"
    }
];
